(function(a){var fa=function(x){async function U(){const b=document.querySelectorAll('img:not([alt]), img[alt=""]');for(const d of b)try{const e=await V(d.src);d.setAttribute("alt",e)}catch(e){}}var c={},f={},B=80,n=80,p=0,u=100,y=0,v=0,r=0,t=a("body"),C=0,D=0,E=0,z=0,R="",O=0,A=0,P=0,F,G;a("body").css("font-family");var H=null,Q=function(b,d){for(i=b.length-1;0<=i;i--)if(d!=b.charAt(i)){b=b.substring(0,i+1);break}return b},L=function(){a(c.fontsizeSelector).filter(function(b){var d=!1;b=0;var e=
1;switch(this.nodeName.toLowerCase()){case "h1":b=100;d=!0;break;case "h2":b=80;e=.8;d=!0;break;case "h3":b=40;e=.6;d=!0;break;case "h4":b=20,e=.4,d=!0}d&&(d=a(this).attr("style")||"",a(this).attr("style",d+";font-size:"+(parseInt(n)+c.fontSizeHeadersIncrement*e+b)+"%"))})},S=function(b){r=parseInt(f.getItem("scr_highcontrast_alternate"))||0;b&&a("#fr_screenreader_highcontrast,#fr_screenreader_highcontrast2,#fr_screenreader_highcontrast3").removeClass("active");var d=function(){t.removeClass("scr_highcontrast");
v=0;f.setItem("scr_highcontrast",v);null===H&&(H=t.attr("style")||"");var g="";a(this).data("rotate")&&(g=" hue-rotate("+parseInt(a(this).data("rotate"))+"deg)");var l="";a(this).data("brightness")&&(l=" brightness("+parseInt(a(this).data("brightness"))+")");t.attr("style",Q(H,";")+";filter: invert(100%)"+g+l)};if(r)if(r&&"undefined"!==typeof b){var e=a(this).data("alternate");e==r?(t.attr("style",H),r=0):(r=e,d.bind(this)(),b&&a(b.target).addClass("active"))}else r&&"undefined"===typeof b&&d.bind(this)();
else d.bind(this)(),r=a(this).data("alternate"),b&&a(b.target).addClass("active");f.setItem("scr_highcontrast_alternate",r)},M=function(b,d){b=b.toUpperCase();var e=b.split(""),g="",l="FEDCBA9876".split(""),k=[];k.A="5";k.B="4";k.C="3";k.D="2";k.E="1";k.F="0";for(i=0;6>i;i++)if(isNaN(e[i]))if(k[e[i]])g+=k[e[i]];else return!1;else g+=l[e[i]];return d&&c.ieHighContrast&&(d=parseInt(b,16),parseInt(g,16)<d)?b:g},I=function(b){var d=/rgba? *\( *([0-9]{1,3}) *, *([0-9]{1,3}) *, *([0-9]{1,3})(, *[0-9]{1,3}[.0-9]*)? *\)/.exec(b);
if(!d)return"FFFFFF";b=Math.round(parseFloat(d[1]));var e=Math.round(parseFloat(d[2]));d=Math.round(parseFloat(d[3]));return(b+65536).toString(16).substring(3).toUpperCase()+(e+65536).toString(16).substring(3).toUpperCase()+(d+65536).toString(16).substring(3).toUpperCase()},W=function(b){b=document.createElement("div");b.style.cssText=" -webkit- -moz- -o- -ms- ".split(" ").join("filter:invert(100%); ");return!!b.style.length&&(void 0===document.documentMode||9<document.documentMode)},T=function(b){a(b);
a.fn.skipElement=function(d){var e=this.css(d);this.css(d,"inherit");var g=this.css(d);if(e!=g&&"000000"!=I(g))return this.css(d,g),!0;this.css(d,e);return!1};a(b).each(function(d,e){if(-1==a.inArray(e.nodeName.toLowerCase(),["script","embed","object"]))if(c.ieHighContrastAdvanced){var g=a(e).css("background-color");d=a(e).css("color");g&&d&&(g=M(I(g)),d=M(I(d),!0),d=(a(e).attr("style")||"")+" background-color:#"+g+" !important; color:#"+d+" !important",a(e).attr("style",d))}else a(e).skipElement("background-color")||
(g=a(e).css("background-color"),d=a(e).css("color"),g&&d&&(g=M(I(g)),d=M(I(d),!0),a(e).css("background-color","#"+g),a(e).css("color","#"+d)))})},X=function(b){b=a(c.skipToContentsSelector);b.length&&a("html, body").animate({scrollTop:b.offset().top},500)};this.buildInterface=function(){var b=a("<div/>").attr("id","accessibility-links").addClass(c.position+" "+c.scrolling+" "+c.templateOrientation);"bottom"==c.targetAppendMode?b.appendTo(c.targetAppendto):"top"==c.targetAppendMode&&b.prependTo(c.targetAppendto);
c.enableDarkMode&&parseInt(f.getItem("scr_toolbar_darkmode"))&&a("#accessibility-links").addClass("scr-toolbar-darkmode");if("accessible.css"==c.template){var d=a("<div/>").attr("id","toolbar_plugin").html('<span class="scaccessibletoolbar-text">'+(c.labeltext||fr_screenreader)+"</span>").addClass("scaccessibletoolbar");"wheelchair"==c.screenreaderIcon&&d.addClass("scr_wheelchair");b.append(d);d=a("<span/>").attr("id","toolbar_closer").html("&#x274c;").attr("data-title",fr_close_toolbar).attr("aria-label",
fr_close_toolbar).attr("role","button").addClass("scaccessibletoolbarcloser");a("#toolbar_plugin").append(d)}var e=a("<div/>").attr("id","text_plugin").attr("title"," - "+(c.labeltext||fr_screenreader)+" - ").addClass("scbasebin screenreader text");c.showlabel||e.addClass("scr_nolabel");"wheelchair"==c.screenreaderIcon&&e.addClass("scr_wheelchair");"custom"==c.screenreaderIcon&&e.addClass("scr_customicon");b.append(e);c.screenreader&&(d=a("<div/>").attr("id","volume_plugin").addClass("scbasebin"),
b.append(d));d=a("<div/>").attr("id","speaker_plugin").addClass("scbasebin speaker");b.append(d);var g=a("<div/>").css("clear","both").attr("id","scr_clearer");b.append(g);c.showlabel&&(b=a("<span/>").addClass("fr_label startapp").text(c.labeltext||fr_screenreader),e.append(b));c.screenreader&&(b=a("<button/>").attr({id:"fr_screenreader_play",title:" - "+fr_screenreader_play+" - ","aria-label":" - "+fr_screenreader_play+" - ",role:"button",accesskey:c.accesskey_play}).addClass("pinnable").text(fr_screenreader_play),
d.append(b),b=a("<button/>").attr({id:"fr_screenreader_pause",title:" - "+fr_screenreader_pause+" - ","aria-label":" - "+fr_screenreader_pause+" - ",role:"button",accesskey:c.accesskey_pause}).addClass("pinnable").text(fr_screenreader_pause),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_stop",title:" - "+fr_screenreader_stop+" - ","aria-label":" - "+fr_screenreader_stop+" - ",role:"button",accesskey:c.accesskey_stop}).addClass("pinnable").text(fr_screenreader_stop),d.append(b));"accessible.css"==
c.template&&(b=a("<div/>").attr({id:"sc-section-audio"}).addClass("sc-section"),b.append('<div class="sc-section-title" aria-label="'+fr_text_reader+'">'+fr_text_reader+"</div>"),d.append(b),e=a("#fr_screenreader_play, #fr_screenreader_pause, #fr_screenreader_stop").clone(!0,!0).end().remove(),b.append(e),e=a("#volume_plugin").clone(!0,!0).end().remove(),b.append(e),c.enableDarkMode&&(b=a("<span/>").attr("id","toolbar_darkmode").html('<svg class="scr-darkmode" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 122.56 122.88"><defs><style>.cls-1{fill-rule:evenodd;}</style></defs><title>night</title><path class="cls-1" d="M121.85,87.3A64.31,64.31,0,1,1,36.88.4c2.94-1.37,5.92.91,4.47,4.47a56.29,56.29,0,0,0,75.75,77.4l.49-.27a3.41,3.41,0,0,1,4.61,4.61l-.35.69ZM92.46,74.67H92A16.11,16.11,0,0,0,76.2,58.93v-.52a15.08,15.08,0,0,0,11-4.72,15.19,15.19,0,0,0,4.72-11h.51a15.12,15.12,0,0,0,4.72,11,15.12,15.12,0,0,0,11,4.72v.51A16.13,16.13,0,0,0,92.46,74.67Zm10.09-46.59h-.27a7.94,7.94,0,0,0-2.49-5.81A7.94,7.94,0,0,0,94,19.78v-.27A7.94,7.94,0,0,0,99.79,17a8,8,0,0,0,2.49-5.8h.27A8,8,0,0,0,105,17a8,8,0,0,0,5.81,2.49v.27A8,8,0,0,0,105,22.27a7.94,7.94,0,0,0-2.49,5.81Zm-41.5,8h-.41a12.06,12.06,0,0,0-3.78-8.82A12.06,12.06,0,0,0,48,23.5v-.41a12.07,12.07,0,0,0,8.82-3.78,12.09,12.09,0,0,0,3.78-8.82h.41a12.08,12.08,0,0,0,3.77,8.82,12.09,12.09,0,0,0,8.83,3.78v.41a12.09,12.09,0,0,0-8.83,3.78,12.08,12.08,0,0,0-3.77,8.82Z"/></svg>').attr("data-title",
fr_dark_mode).attr("aria-label",fr_dark_mode).attr("role","button").addClass("scaccessibletoolbarcloser"),a("#sc-section-audio").append(b),a("#toolbar_darkmode").on("click",function(h){h=0;var q=a("#accessibility-links");q.toggleClass("scr-toolbar-darkmode");q.hasClass("scr-toolbar-darkmode")&&(h=1);f.setItem("scr_toolbar_darkmode",h)})),c.enableAccessibilityStatement&&(b=a("<a/>").attr("id","toolbar_accessibility_statement").text(c.enableAccessibilityStatementText).attr("href",c.enableAccessibilityStatementLink).attr("download",
c.enableAccessibilityStatementLink.substring(c.enableAccessibilityStatementLink.lastIndexOf("/")+1)).addClass("scaccessibletoolbarstatement"),c.enableDarkMode&&b.addClass("darkmode"),a("#sc-section-audio").append(b)));c.fontsize&&(b=a("<button/>").attr({id:"fr_screenreader_font_increase",title:" - "+fr_increase+" - ","aria-label":" - "+fr_increase+" - ",role:"button",accesskey:c.accesskey_increase,"data-value":"1"}).addClass("sizable").text(fr_increase),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_font_decrease",
title:" - "+fr_decrease+" - ","aria-label":" - "+fr_decrease+" - ",role:"button",accesskey:c.accesskey_decrease,"data-value":"-1"}).addClass("sizable").text(fr_decrease),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_font_reset",title:" - "+fr_reset+" - ","aria-label":" - "+fr_reset+" - ",role:"button",accesskey:c.accesskey_reset,"data-value":"0"}).addClass("resizable").text(fr_reset),d.append(b),"accessible.css"==c.template&&(b=c.fontsizeDefault,f.getItem("scr_fontsize"),b=parseInt(n-b),
e=0<b?"+":"-",0!=b&&(0<b?a("#fr_screenreader_font_increase").append('<div class="scfontsizelabel">'+e+b+"%</div>"):a("#fr_screenreader_font_decrease").append('<div class="scfontsizelabel">'+b+"%</div>")),b=a("<div/>").attr({id:"sc-section-fontsize"}).addClass("sc-section"),b.append('<div class="sc-section-title" aria-label="'+fr_font_sizing+'">'+fr_font_sizing+"</div>"),d.append(b),e=a("#fr_screenreader_font_increase, #fr_screenreader_font_decrease, #fr_screenreader_font_reset").clone(!0,!0).end().remove(),
b.append(e)));c.dyslexicFont&&(b=a("<button/>").attr({id:"fr_screenreader_font_family",title:" - "+fr_dyslexic_title+" - ","aria-label":" - "+fr_dyslexic_title+" - ",role:"button",accesskey:c.accesskey_dyslexic,"data-value":"0"}).text(fr_dyslexic_title),d.append(b));c.grayHues&&(b=a("<button/>").attr({id:"fr_screenreader_gray_hues",title:" - "+fr_gray_hues+" - ","aria-label":" - "+fr_gray_hues+" - ",role:"button",accesskey:c.accesskey_grayhues}).text(fr_gray_hues),d.append(b));c.bigCursor&&(b=a("<button/>").attr({id:"fr_screenreader_bigcursor",
title:" - "+fr_big_cursor+" - ","aria-label":" - "+fr_big_cursor+" - ",role:"button",accesskey:c.accesskey_bigcursor}).text(fr_big_cursor),d.append(b));c.readingGuides&&(b=a("<button/>").attr({id:"fr_screenreader_reading_guides",title:" - "+fr_reading_guides_title+" - ","aria-label":" - "+fr_reading_guides_title+" - ",role:"button",accesskey:c.accesskey_reading_guides}).text(fr_reading_guides_title),d.append(b),(z=!!parseInt(f.getItem("scr_reading_guides"))||0)&&a("#fr_screenreader_reading_guides").trigger("click",
1));c.readability&&(b=a("<button/>").attr({id:"fr_screenreader_readability",title:" - "+fr_readability_title+" - ","aria-label":" - "+fr_readability_title+" - ",role:"button",accesskey:c.accesskey_readability}).text(fr_readability_title),d.append(b));c.hideImages&&(b=a("<button/>").attr({id:"fr_screenreader_hideimages",title:" - "+fr_hideimages_title+" - ","aria-label":" - "+fr_hideimages_title+" - ",role:"button",accesskey:c.accesskey_hideimages}).text(fr_hideimages_title),d.append(b),(A=!!parseInt(f.getItem("scr_hideimages"))||
0)&&a("#fr_screenreader_hideimages").trigger("click",1));c.showSkipToContents&&(b=a("<button/>").attr({id:"fr_screenreader_skiptocontents",title:" - "+fr_showskiptocontents_title+" - ","aria-label":" - "+fr_showskiptocontents_title+" - ",role:"button",accesskey:c.accesskey_skiptocontents}).text(fr_showskiptocontents_title),d.append(b));c.spacingSize&&(b=a("<button/>").attr({id:"fr_screenreader_spacing_increase",title:" - "+fr_spacing_increase+" - ","aria-label":" - "+fr_spacing_increase+" - ",role:"button",
accesskey:c.accesskey_spacingsize_increase,"data-value":"1"}).addClass("spacingsizable").text(fr_spacing_increase),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_spacing_decrease",title:" - "+fr_spacing_decrease+" - ","aria-label":" - "+fr_spacing_decrease+" - ",role:"button",accesskey:c.accesskey_spacingsize_decrease,"data-value":"-1"}).addClass("spacingsizable").text(fr_spacing_decrease),d.append(b),"accessible.css"==c.template&&(b=f.getItem("scr_spacingsize"))&&0<b&&a("#fr_screenreader_spacing_increase").append('<div class="scspacingsizelabel">+'+
10*b+"%</div>"));"accessible.css"==c.template&&(b=a("#fr_screenreader_font_family, #fr_screenreader_gray_hues, #fr_screenreader_bigcursor, #fr_screenreader_reading_guides, #fr_screenreader_readability, #fr_screenreader_hideimages, #fr_screenreader_skiptocontents, #fr_screenreader_spacing_increase, #fr_screenreader_spacing_decrease").clone(!0,!0).end().remove(),b.length&&(e=a("<div/>").attr({id:"sc-section-enhancement"}).addClass("sc-section"),e.append('<div class="sc-section-title" aria-label="'+
fr_accessibility_enhancements+'">'+fr_accessibility_enhancements+"</div>"),d.append(e),e.append(b)));c.pageZoom&&"vertical"==c.templateOrientation&&(b=a("<button/>").attr({id:"fr_screenreader_pagezoom_increase",title:" - "+fr_pagezoom_increase+" - ","aria-label":" - "+fr_pagezoom_increase+" - ",role:"button",accesskey:c.accesskey_pagezoomsize_increase,"data-value":"1"}).addClass("zoomsizable").text(fr_pagezoom_increase),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_pagezoom_decrease",title:" - "+
fr_pagezoom_decrease+" - ","aria-label":" - "+fr_pagezoom_decrease+" - ",role:"button",accesskey:c.accesskey_pagezoomsize_decrease,"data-value":"-1"}).addClass("zoomsizable").text(fr_pagezoom_decrease),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_pagezoom_reset",title:" - "+fr_pagezoom_reset+" - ","aria-label":" - "+fr_pagezoom_reset+" - ",role:"button",accesskey:c.accesskey_pagezoomsize_reset,"data-value":"0"}).addClass("zoomresizable").text(fr_pagezoom_reset),d.append(b),"accessible.css"==
c.template&&(f.getItem("scr_zoomsize"),b=parseInt(u-100),e=0<b?"+":"-",0!=b&&(0<b?a("#fr_screenreader_pagezoom_increase").append('<div class="sczoomsizelabel">'+e+b+"%</div>"):a("#fr_screenreader_pagezoom_decrease").append('<div class="sczoomsizelabel">'+b+"%</div>")),(b=f.getItem("scr_pagezoom"))&&0<b&&a("#fr_screenreader_pagezoom_increase").append('<div class="scspacingsizelabel">+'+10*b+"%</div>"),b=a("<div/>").attr({id:"sc-section-pagezoom"}).addClass("sc-section"),b.append('<div class="sc-section-title" aria-label="'+
fr_page_zoom+'">'+fr_page_zoom+"</div>"),d.append(b),e=a("#fr_screenreader_pagezoom_increase, #fr_screenreader_pagezoom_decrease, #fr_screenreader_pagezoom_reset").clone(!0,!0).end().remove(),b.append(e)));b=0;c.screenreader||(b=100);c.dyslexicFont||(b+=35);c.grayHues||(b+=35);c.bigCursor||(b+=35);c.readingGuides||(b+=35);c.readability||(b+=35);c.showSkipToContents||(b+=35);c.spacingSize||(b+=70);if(c.highcontrast){e=a("<button/>").attr({id:"fr_screenreader_highcontrast",title:" - "+fr_highcontrast+
" - ","aria-label":" - "+fr_highcontrast+" - ",role:"button",accesskey:c.accesskey_highcontrast,"data-value":"0"}).text(fr_highcontrast);v&&e.addClass("active");d.append(e);if(e=c.highcontrastAlternate&&W())if(g=a("<button/>").attr({id:"fr_screenreader_highcontrast2",title:" - "+fr_highcontrast+" - ","aria-label":" - "+fr_highcontrast+" - ",role:"button",accesskey:c.accesskey_highcontrast2,"data-alternate":"1","data-rotate":c.colorHue}).text(fr_highcontrast),d.append(g),g=a("<button/>").attr({id:"fr_screenreader_highcontrast3",
title:" - "+fr_highcontrast+" - ","aria-label":" - "+fr_highcontrast+" - ",role:"button",accesskey:c.accesskey_highcontrast3,"data-alternate":"2","data-rotate":c.colorHue,"data-brightness":c.colorBrightness}).text(fr_highcontrast),d.append(g),r=parseInt(f.getItem("scr_highcontrast_alternate"))||0)g=a("button[data-alternate="+r+"]").addClass("active"),S.call(g);c.fontsize&&e?a("#speaker_plugin").css("width",parseInt(605-b)+"px"):c.fontsize?a("#speaker_plugin").css("width",parseInt(540-b)+"px"):!c.fontsize&&
e&&a("#speaker_plugin").css("width",parseInt(510-b)+"px");"accessible.css"==c.template&&(b=a("<div/>").attr({id:"sc-section-highcontrast"}).addClass("sc-section"),b.append('<div class="sc-section-title" aria-label="'+fr_high_contrast_color+'">'+fr_high_contrast_color+"</div>"),d.append(b),e=a("#fr_screenreader_highcontrast, #fr_screenreader_highcontrast2, #fr_screenreader_highcontrast3").clone(!0,!0).end().remove(),b.append(e))}else c.fontsize?a("#speaker_plugin").css("width",parseInt(425-b)+"px"):
a("#speaker_plugin").css("width",parseInt(315-b)+"px");c.customColors&&"accessible.css"==c.template&&(b=a("<button/>").attr({id:"fr_screenreader_text_color",title:" - "+fr_text_color+" - ","aria-label":" - "+fr_text_color+" - ",role:"button",accesskey:c.accesskey_change_text_color}).addClass("scr-custom-color").text(fr_text_color),d.append(b),b=a("<button/>").attr({id:"fr_screenreader_background_color",title:" - "+fr_background_color+" - ","aria-label":" - "+fr_background_color+" - ",role:"button",
accesskey:c.accesskey_change_background_color}).addClass("scr-custom-color").text(fr_background_color),d.append(b),b=`
				<div class="scr-color-box">
					<span data-scr-color="#0076B4" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #0076B4 !important;"> </span> 
					<span data-scr-color="#7A549C" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #7A549C !important;"> </span> 
					<span data-scr-color="#C83733" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #C83733 !important;"> </span> 
					<span data-scr-color="#D07021" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #D07021 !important;"> </span> 
					<span data-scr-color="#26999F" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #26999F !important;"> </span> 
					<span data-scr-color="#4D7831" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #4D7831 !important;"> </span> 
					<span data-scr-color="#ffffff" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #ffffff !important;"> </span> 
					<span data-scr-color="#000000" class="scr-color-selection" role="button" tabindex="0" aria-label="${fr_background_color_desc}" style="background-color: #000000 !important;"> </span> 
					<div class="scr-color-selection-reset" role="button" tabindex="0"> ${fr_custom_color_reset} </div>
				</div>`,a("button.scr-custom-color").append(b),b=a("<div/>").attr({id:"sc-section-customcolors"}).addClass("sc-section"),b.append('<div class="sc-section-title" aria-label="'+fr_custom_colors+'">'+fr_custom_colors+"</div>"),d.append(b),d=a("#fr_screenreader_text_color, #fr_screenreader_background_color").clone(!0,!0).end().remove(),b.append(d),a("span.scr-color-selection").on("click",function(h){h=a(this);var q=h.parents("button.scr-custom-color").attr("id"),m=h.data("scr-color");"fr_screenreader_text_color"==
q?(h.hasClass("scr-color-selection-enabled")?(document.querySelector("body").style.removeProperty("color"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(J,w){w.style.removeProperty("color")}),h.removeClass("scr-color-selection-enabled")):(document.querySelector("body").style.setProperty("color",m,"important"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(J,w){w.style.setProperty("color",m,"important")}),a("#fr_screenreader_text_color span.scr-color-selection").removeClass("scr-color-selection-enabled"),
h.addClass("scr-color-selection-enabled")),f.setItem("scr_custom_text_color",m)):"fr_screenreader_background_color"==q&&(h.hasClass("scr-color-selection-enabled")?(document.querySelector("body").style.removeProperty("background"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(J,w){w.style.removeProperty("background")}),h.removeClass("scr-color-selection-enabled")):(document.querySelector("body").style.setProperty("background",m,"important"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(J,
w){w.style.setProperty("background",m,"important")}),a("#fr_screenreader_background_color span.scr-color-selection").removeClass("scr-color-selection-enabled"),h.addClass("scr-color-selection-enabled")),f.setItem("scr_custom_background_color",m))}),a("div.scr-color-selection-reset").on("click",function(h){h=a(this).parents("button.scr-custom-color").attr("id");"fr_screenreader_text_color"==h?(a("span.scr-color-selection").removeClass("scr-color-selection-enabled"),document.querySelector("body").style.removeProperty("color"),
c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(q,m){m.style.removeProperty("color")}),f.removeItem("scr_custom_text_color")):"fr_screenreader_background_color"==h&&(a("span.scr-color-selection").removeClass("scr-color-selection-enabled"),document.querySelector("body").style.removeProperty("background"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(q,m){m.style.removeProperty("background")}),f.removeItem("scr_custom_background_color"))}),a("#fr_screenreader_background_color, #fr_screenreader_text_color").on("click",
function(h){h.stopPropagation();if(!a(h.target).hasClass("scr-custom-color")&&!a(h.target).hasClass("scr-color-box"))return!1;h=a(h.target).hasClass("scr-custom-color")?a(h.target):a(h.target).parent("button.scr-custom-color");var q=a("span.scr-color-selection.scr-color-selection-enabled",h);q.length?q.next().trigger("click"):a("div.scr-color-box > span:first-child",h).trigger("click")}));"custom.css"==c.template?(a("#speaker_plugin button").css("background-color",c.toolbarBgcolor),a("#accessibility-links").css("background",
"transparent")):a("#accessibility-links").css("background-color",c.toolbarBgcolor);"vertical"==c.templateOrientation&&"custom.css"!=c.template&&a("#text_plugin").css("background-color",c.toolbarBgcolor);d=c.toolbarBgcolor.toLowerCase();"accessible.css"!=c.template||"#eeeeee"!=d&&"#eee"!=d||(a("#text_plugin").css("background-color","#004fce"),a("#toolbar_plugin").css("background-color","#004fce"),a("#toolbar_closer").css({color:"transparent","text-shadow":"#004fce 0px 0px 0px"}),a("svg.scr-darkmode").css("fill",
"#004fce"));"accessible.css"==c.template&&"#eeeeee"!=d&&"#eee"!=d&&(a("#accessibility-links").css("background-color","#EEEEEE"),a("#text_plugin").css("background-color",c.toolbarBgcolor),a("#toolbar_plugin").css("background-color",c.toolbarBgcolor),a("#toolbar_closer").css({color:"transparent","text-shadow":c.toolbarBgcolor+" 0px 0px 0px"}),a("svg.scr-darkmode").css("fill",c.toolbarBgcolor));"accessible.css"==c.template&&(a("#speaker_plugin > button").removeAttr("title"),d=a("#text_plugin").attr("title"),
a("#text_plugin").removeAttr("title"),a("#text_plugin").attr("aria-label",d).attr("role","button"));if(screenReaderConfigOptions.useMinimizedToolbar&&(screenReaderConfigOptions.mobileDeviceDetected||!screenReaderConfigOptions.mobileDeviceDetected&&!screenReaderConfigOptions.minimizedToolbarOnlyMobile)){d=a("#volume_plugin").width();b=a("#speaker_plugin").width();e=a("#accessibility-links").width();var l=parseInt(d+b);"vertical"==c.templateOrientation&&(l=parseInt(b));"accessible.css"==c.template&&
(l=parseInt(e));var k=0,K="+";d=a(window).width();d<l&&"accessible.css"!=c.template&&(l=d-80);a("#text_plugin").attr("accesskey",screenReaderConfigOptions.accesskey_minimized);a("#toolbar_closer").on("click",function(h){a("#text_plugin").trigger("click")});if(c.fontsizeMinimizedToolbar&&"closed"==screenReaderConfigOptions.statusMinimizedToolbar)a("#text_plugin").on("click",function(h){a("body").css("font-size",n+"%");c.fontsizeSelector&&(fontSizeInline=";font-size:100%",L());h=a(c.fontsizeSelector);
a.each(h,function(q,m){fontSizeInline=-1!=a.inArray(m.nodeName.toLowerCase(),["h1","h2","h3","h4"])?"":";font-size:100%";q=a(m).attr("style")||"";a(m).attr("style",Q(q,";")+fontSizeInline)})});switch(c.position){case "bottomright":case "topright":a("#text_plugin span.fr_label").css({cursor:"pointer"});if("closed"==screenReaderConfigOptions.statusMinimizedToolbar){if(a("#accessibility-links").css({right:"-"+(l+2)+"px"}).removeClass("screenreader-open").addClass("screenreader-closed"),"accessible.css"==
c.template)a(window).on("resize",function(){var h=a("#accessibility-links.screenreader-closed");h.length&&(h=h.width(),l=parseInt(h),a("#accessibility-links").css({right:"-"+(l+2)+"px"}))})}else a("#speaker_plugin, #volume_plugin").css({opacity:1}),a("#accessibility-links").removeClass("screenreader-closed").addClass("screenreader-open"),k=l+2,K="-";a("#text_plugin").css({cursor:"pointer"}).on("click",function(h){k&&a("#speaker_plugin, #volume_plugin").animate({opacity:0},300);a("#accessibility-links").animate({right:K+
k},500,function(){k=k?0:l+2;K="-";k?a(this).removeClass("screenreader-closed").addClass("screenreader-open"):a(this).removeClass("screenreader-open").addClass("screenreader-closed")});k||setTimeout(function(){a("#speaker_plugin, #volume_plugin").animate({opacity:1},300)},300)});break;case "topleft":case "bottomleft":"closed"==screenReaderConfigOptions.statusMinimizedToolbar?(a("#accessibility-links").removeClass("screenreader-open").addClass("screenreader-closed"),a("#volume_plugin,#speaker_plugin,#toolbar_plugin").hide()):
a("#accessibility-links").removeClass("screenreader-closed").addClass("screenreader-open"),a("#text_plugin span.fr_label").css({cursor:"pointer"}),a("#text_plugin").css({cursor:"pointer"}).on("click",function(h){a("#volume_plugin,#speaker_plugin,#toolbar_plugin").fadeToggle();a("#accessibility-links").hasClass("screenreader-open")?a("#accessibility-links").removeClass("screenreader-open").addClass("screenreader-closed"):a("#accessibility-links").removeClass("screenreader-closed").addClass("screenreader-open")})}}else switch(c.position){case "bottomright":case "topright":a("#speaker_plugin, #volume_plugin").css({opacity:1})}"accessible.css"!=
c.template&&"vertical"==c.templateOrientation&&(d=a("#text_plugin"),b=a("#volume_plugin"),e=d.clone(!0,!0),g=b.clone(!0,!0),a("#scr_clearer").before(e).before(g),d.remove(),b.remove())};this.startTTSEngine=function(){new jQuery.frTTSEngine(c);return!0};var Y=function(){a(document).on("click",".sizable",function(b){b=parseInt(a(this).data("value"));n=parseInt(n)+parseInt(5*b);n>c.fontsizeMax?n=c.fontsizeMax:n<c.fontsizeMin&&(n=c.fontsizeMin);a("body").css("font-size",n+"%");c.fontsizeSelector&&L();
f.setItem("scr_fontsize",n);if("accessible.css"==c.template){b=parseInt(n-B);var d=0<b?"+":"-";0!=b?(a("div.scfontsizelabel").remove(),0<b?a("#fr_screenreader_font_increase").append('<div class="scfontsizelabel">'+d+b+"%</div>"):a("#fr_screenreader_font_decrease").append('<div class="scfontsizelabel">'+b+"%</div>")):a("div.scfontsizelabel").remove()}});a(document).on("click",".resizable",function(b){"all"==c.resetButtonBehavior&&(parseInt(f.getItem("scr_highcontrast"))?a("#fr_screenreader_highcontrast").trigger("click"):
(b=parseInt(f.getItem("scr_highcontrast_alternate"))||0,1==b&&a("#fr_screenreader_highcontrast2").trigger("click"),2==b&&a("#fr_screenreader_highcontrast3").trigger("click")),parseInt(f.getItem("scr_dyslexicfont"))&&a("#fr_screenreader_font_family").trigger("click"),parseInt(f.getItem("scr_grayhues"))&&a("#fr_screenreader_gray_hues").trigger("click"),parseInt(f.getItem("scr_bigcursor"))&&a("#fr_screenreader_bigcursor").trigger("click"),parseInt(f.getItem("scr_zoomsize"))&&a("#fr_screenreader_pagezoom_reset").trigger("click"));
"accessible.css"==c.template&&a("div.scfontsizelabel,div.scspacingsizelabel").remove();n=B;a("body").css("font-size",B+"%");if(parseInt(f.getItem("scr_spacingsize"))||parseInt(f.getItem("scr_final_lineheight")))a("body").css({"word-spacing":"inherit","letter-spacing":"inherit","line-height":f.getItem("scr_initial_lineheight")}),f.setItem("scr_spacingsize",0),p=0,f.removeItem("scr_final_lineheight");c.fontsizeSelector&&L();f.setItem("scr_fontsize",B)});a(document).on("click",".zoomsizable",function(b){b=
parseInt(a(this).data("value"));u=parseInt(u)+parseInt(5*b);a("html").css("zoom",u+"%");f.setItem("scr_zoomsize",u);if("accessible.css"==c.template){b=parseInt(u-100);var d=0<b?"+":"-";0!=b?(a("div.sczoomsizelabel").remove(),0<b?a("#fr_screenreader_pagezoom_increase").append('<div class="sczoomsizelabel">'+d+b+"%</div>"):a("#fr_screenreader_pagezoom_decrease").append('<div class="sczoomsizelabel">'+b+"%</div>")):a("div.sczoomsizelabel").remove()}});a(document).on("click",".zoomresizable",function(b){"accessible.css"==
c.template&&a("div.sczoomsizelabel").remove();u=100;a("html").css("zoom","100%");f.removeItem("scr_zoomsize",100)});a(document).on("click",".spacingsizable",function(b){b=parseInt(a(this).data("value"));var d=a("body").css("line-height");p=parseInt(p)+parseInt(b);y=parseFloat(d)?parseFloat(d)+parseInt(b):16+parseInt(b);p>c.spacingSizeMax?p=c.spacingSizeMax:p<c.spacingSizeMin?p=c.spacingSizeMin:(f.getItem("scr_initial_lineheight")||f.setItem("scr_initial_lineheight",d),a("body").css({"word-spacing":2*
p+"px","letter-spacing":p+"px","line-height":y+"px"}),f.setItem("scr_spacingsize",p),f.setItem("scr_final_lineheight",y),"accessible.css"==c.template&&(0<p?a("#fr_screenreader_spacing_increase").append('<div class="scspacingsizelabel">+'+10*p+"%</div>"):a("div.scspacingsizelabel").remove()))});a(document).on("click","#fr_screenreader_highcontrast",function(b){(v=!!parseInt(f.getItem("scr_highcontrast"))||0)?(t.removeClass("scr_highcontrast"),"ActiveXObject"in window&&(v=0,window.location.reload()),
a(this).removeClass("active"),v=0):(r&&(t.attr("style",H),r=0,f.setItem("scr_highcontrast_alternate",r)),t.addClass("scr_highcontrast"),"ActiveXObject"in window&&T("body, body *:not(#accessibility-links, #accessibility-links *, div.shapes)"),a("#fr_screenreader_highcontrast2,#fr_screenreader_highcontrast3").removeClass("active"),a(this).addClass("active"),v=1);f.setItem("scr_highcontrast",v)});a(document).on("click","#fr_screenreader_font_family",function(b){(C=!!parseInt(f.getItem("scr_dyslexicfont"))||
0)?(a("body").removeClass("scr_dyslexic"),c.fontsizeSelector&&(b=a(c.fontsizeSelector),a.each(b,function(d,e){d=a(e).attr("style")||"";a(e).attr("style",d.replace(";font-family:OpenDyslexic",""))})),C=0):(a("body").addClass("scr_dyslexic"),c.fontsizeSelector&&(b=a(c.fontsizeSelector),a.each(b,function(d,e){d=a(e).attr("style")||"";a(e).attr("style",d+";font-family:OpenDyslexic")})),C=1);f.setItem("scr_dyslexicfont",C)});a(document).on("click","#fr_screenreader_gray_hues",function(b){(D=!!parseInt(f.getItem("scr_grayhues"))||
0)?(t.removeClass("scr_grayhues"),D=0):(t.addClass("scr_grayhues"),D=1);f.setItem("scr_grayhues",D)});a(document).on("click","#fr_screenreader_bigcursor",function(b){(E=!!parseInt(f.getItem("scr_bigcursor"))||0)?(a("body").removeClass("scr_bigcursor"),E=0):(a("body").addClass("scr_bigcursor"),E=1);f.setItem("scr_bigcursor",E)});a(document).on("click","#fr_screenreader_reading_guides",function(b,d){b=function(e){e="touchmove"==e.type?e.changedTouches[0].clientY:e.y;a("#sc_read_guide_bar").css("top",
e-15)};z=!!parseInt(f.getItem("scr_reading_guides"))||0;!z||d?(a("body").addClass("scr_reading_guides"),d=document.createElement("div"),d.id="sc_read_guide_bar",d.classList.add("sc_read_guide_bar"),a("body").append(d),document.body.addEventListener("touchmove",b,!1),document.body.addEventListener("mousemove",b,!1),z=1):(a("body").removeClass("scr_reading_guides"),a("#sc_read_guide_bar").remove(),document.body.removeEventListener("touchmove",b,!1),document.body.removeEventListener("mousemove",b,!1),
z=0);f.setItem("scr_reading_guides",z)});a(document).on("click","#fr_screenreader_readability",function(b){if(O)a("body").removeClass("scr_readability"),a("div.sc-readability").remove(),a("body").replaceWith(R[0]),t=a("body"),O=0;else{R=a("body").clone();a("body").addClass("scr_readability");if(b=a(c.readabilitySelector).html())a("body").empty(),a("body").append('<div class="sc-readability">'+b+"</div>");O=1}});a(document).on("click","#fr_screenreader_hideimages",function(b,d){A=!!parseInt(f.getItem("scr_hideimages"))||
0;P=c.hideAlsoVideosIframes;!A||d?(a("body").addClass("scr_hideimages"),P&&a("body").addClass("scr_hidevideosiframes"),A=1):(a("body").removeClass("scr_hideimages"),P&&a("body").removeClass("scr_hidevideosiframes"),A=0);f.setItem("scr_hideimages",A)});a(document).on("click","#fr_screenreader_highcontrast2, #fr_screenreader_highcontrast3",S);if(c.showSkipToContents)a(document).on("click","#fr_screenreader_skiptocontents",X)},V=async function(b){if(!b)return"";let d={};try{d=JSON.parse(localStorage.getItem("screenReaderAltMapping"))||
{}}catch(k){d={}}for(var e=5381,g=0;g<b.length;g++)e=(e<<5)+e+b.charCodeAt(g);e=(e>>>0).toString(36);if(d[e])return d[e];g=atob(c.generateMissingImagesAltChatgptApikey);let l="";for(let k=0;k<g.length;k++)l+=String.fromCharCode(g.charCodeAt(k)^"screenreader".charCodeAt(k%12));g=l.split("").reverse().join("");if(!g.trim())return"";b=await fetch("https://api.openai.com/v1/chat/completions",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${g}`},body:JSON.stringify({model:c.generateMissingImagesAltChatgptModel,
messages:[{role:"user",content:`Describe the content of this image in a short, clear sentence using the language matching the code '${screenReaderConfigOptions.langCode}': ${b}`}],max_completion_tokens:3600})});if(!b.ok)return"";b=(await b.json()).choices[0].message.content.trim();d[e]=b;localStorage.setItem("screenReaderAltMapping",JSON.stringify(d));return b},Z=function(){let b=1;Array.from(document.querySelectorAll("h1, h2, h3, h4, h5, h6")).forEach((d,e)=>{let g=parseInt(d.tagName.replace("H",
""),10);0===e&&1!==g?g=1:g>b+1&&(g=b+1);if(g!==parseInt(d.tagName.replace("H",""),10)){const l=document.createElement(`h${g}`);Array.from(d.attributes).forEach(k=>{l.setAttribute(k.name,k.value)});l.innerHTML=d.innerHTML;d.replaceWith(l)}b=g})},aa=function(b,d){function e(m,J,w){m=[m,J,w].map(N=>{N/=255;return.03928>=N?N/12.92:Math.pow((N+.055)/1.055,2.4)});return.2126*m[0]+.7152*m[1]+.0722*m[2]}const [g,l,k]=b.match(/\d+/g).map(Number),[K,h,q]=d.match(/\d+/g).map(Number);b=e(g,l,k);d=e(K,h,q);return 4.5<=
(Math.max(b,d)+.05)/(Math.min(b,d)+.05)},ba=function(){document.querySelectorAll("p, h1, h2, h3, h4, h5, h6, span, div, a, li, td, th, label, button").forEach(b=>{if(!b.classList.contains("screenreader_embed_play_button")){var d=window.getComputedStyle(b).backgroundColor,e=window.getComputedStyle(b).color;aa(d,e)||(b.style.color="#000")}})},ca=function(){document.querySelectorAll("nav:not([role])").forEach(d=>{d.setAttribute("role","navigation")});var b=document.querySelector("main:not([role]),#content:not([role])");
b?b.setAttribute("role","main"):(b=a(c.skipToContentsSelector),b.length&&!b.get(0).hasAttribute("role")&&b.get(0).setAttribute("role","main"))},da=function(){document.querySelectorAll("input, textarea, select").forEach(b=>{var d=b.getAttribute("id");d&&document.querySelector(`label[for="${d}"]`)||b.closest("label")||(d=b.getAttribute("placeholder")||"Input field",b.setAttribute("aria-label",d))})},ea=function(){let b=Array.from(document.querySelectorAll('\n\t\t\t    a[href],\n\t\t\t    area[href],\n\t\t\t    input:not([disabled]):not([type="hidden"]),\n\t\t\t    select:not([disabled]),\n\t\t\t    textarea:not([disabled]),\n\t\t\t    button:not([disabled]),\n\t\t\t    iframe,\n\t\t\t    [tabindex]:not([tabindex="-1"]),\n\t\t\t    [contenteditable="true"]\n\t\t\t  '));
b=b.filter(d=>{d=window.getComputedStyle(d);return"none"!==d.display&&"hidden"!==d.visibility});b.forEach((d,e)=>{e+=1;d.tabIndex=e;d.setAttribute("tabindex",e)})};(function(){"undefined"===typeof fr_close_toolbar&&(window.fr_close_toolbar="Close accessibility interface",window.fr_text_reader="Text Reader",window.fr_font_sizing="Font sizing",window.fr_accessibility_enhancements="Accessibility enhancements",window.fr_high_contrast_color="High contrast color",window.fr_reading_guides_title="Reading guide");
"undefined"===typeof fr_dark_mode&&(window.fr_volume="Volume",window.fr_dark_mode="Toggle dark mode",window.fr_page_zoom="Page zoom",window.fr_pagezoom_increase="Increase zoom",window.fr_pagezoom_decrease="Decrease zoom",window.fr_pagezoom_reset="Reset zoom");a.extend(c,x);"session"==c.selectedStorage?f=window.sessionStorage:"local"==c.selectedStorage&&(f=window.localStorage);c.rootTarget&&(t=a("html"));void 0===jQuery.frTTSEngine&&jQuery('script[src*="tts.js"]').clone().appendTo("body");if(c.autoBackgroundColor){var b=
a("body").css("background-color");a("html").css("background-color",b)}B=n=c.fontsizeDefault;(b=f.getItem("scr_fontsize"))&&(n=b);if(b=f.getItem("scr_zoomsize"))u=b,a("html").css("zoom",u+"%");var d="";c.spacingSize&&(p=parseInt(f.getItem("scr_spacingsize"))||0,0<p&&a("body").css({"word-spacing":2*p+"px","letter-spacing":p+"px"}),y=parseFloat(f.getItem("scr_final_lineheight"))||0,0<y&&a("body").css({"line-height":y+"px"}),c.fontsizeSelector&&(d=";word-spacing:inherit;letter-spacing:inherit;line-height:inherit"));
var e="",g=!!screenReaderConfigOptions.useMinimizedToolbar&&!!c.fontsizeMinimizedToolbar&&"closed"==screenReaderConfigOptions.statusMinimizedToolbar;c.fontsize&&!g&&(a("body").css("font-size",n+"%"),c.fontsizeSelector&&(e=";font-size:100%",L()));if(c.fontsize||c.spacingSize)b=a(c.fontsizeSelector),a.each(b,function(l,k){e=-1!=a.inArray(k.nodeName.toLowerCase(),["h1","h2","h3","h4"])||g?"":";font-size:100%";l=a(k).attr("style")||"";a(k).attr("style",Q(l,";")+e+d)});if(v=!!parseInt(f.getItem("scr_highcontrast"))||
0)t.addClass("scr_highcontrast"),"ActiveXObject"in window&&T("body, body *:not(#accessibility-links, #accessibility-links *, div.shapes)");if(C=!!parseInt(f.getItem("scr_dyslexicfont"))||0)a("body").addClass("scr_dyslexic"),c.fontsizeSelector&&(b=a(c.fontsizeSelector),a.each(b,function(l,k){l=a(k).attr("style")||"";a(k).attr("style",l+";font-family:OpenDyslexic")}));(D=!!parseInt(f.getItem("scr_grayhues"))||0)&&t.addClass("scr_grayhues");(E=!!parseInt(f.getItem("scr_bigcursor"))||0)&&a("body").addClass("scr_bigcursor");
F=f.getItem("scr_custom_background_color");c.customColors&&"accessible.css"==c.template&&F&&(document.querySelector("body").style.setProperty("background",F,"important"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(l,k){k.style.setProperty("background",F,"important")}),setTimeout(function(){a('#fr_screenreader_background_color span.scr-color-selection[data-scr-color="'+F+'"]').addClass("scr-color-selection-enabled")},1));G=f.getItem("scr_custom_text_color");c.customColors&&
"accessible.css"==c.template&&G&&(document.querySelector("body").style.setProperty("color",G,"important"),c.customColorsCssSelectors&&a(c.customColorsCssSelectors).each(function(l,k){k.style.setProperty("color",G,"important")}),setTimeout(function(){a('#fr_screenreader_text_color span.scr-color-selection[data-scr-color="'+G+'"]').addClass("scr-color-selection-enabled")},1));c.removeLinksTarget&&a("a").removeAttr("target");Y();c.generateMissingImagesAlt&&U();c.fixHeadingsStructure&&Z();c.fixLowContrastText&&
ba();c.fixMissingAriaRoles&&ca();c.fixMissingFormLabels&&da();c.validateAndFixFocusOrder&&ea()}).call(this)};a(function(){var x=!!navigator.msMaxTouchPoints;x=!!("ontouchstart"in window)||x;screenReaderConfigOptions.hideOnMobile&&x||(x&&screenReaderConfigOptions.useMobileReaderEngine&&(screenReaderConfigOptions.readerEngine!=screenReaderConfigOptions.mobileReaderEngine&&(screenReaderConfigOptions.readerEngine=screenReaderConfigOptions.mobileReaderEngine),"proxy"==screenReaderConfigOptions.readerEngine&&
100<parseInt(screenReaderConfigOptions.chunkLength)&&(screenReaderConfigOptions.chunkLength=90),"proxy_virtual"==screenReaderConfigOptions.readerEngine&&300<=parseInt(screenReaderConfigOptions.chunkLength)&&(screenReaderConfigOptions.chunkLength=280)),screenReaderConfigOptions.mobileDeviceDetected=x?!0:!1,window.ScreenReaderMainController=new fa(screenReaderConfigOptions),ScreenReaderMainController.buildInterface(),ScreenReaderMainController.startTTSEngine())})})(jQuery);
